POST http://localhost:8081/holder
Content-Type: application/json

{
  "holderName" : "kim",
  "tel" : "02-2222-3333",
  "address" : "OO시 OO구",
  "company" : "sourcing company"
}

###

POST http://localhost:8081/account
Content-Type: application/json

{
  "holderId" : "a169c61a-1e47-41e8-b673-f33db08b522f"
}

###

POST http://localhost:8081/deposit
Content-Type: application/json

{
  "accountId" : "b19f0aa5-1a28-4a5a-81ea-a967dc7ab41b",
  "holderId" : "a169c61a-1e47-41e8-b673-f33db08b522f",
  "amount" : 200
}

###

POST http://localhost:8081/withdrawal
Content-Type: application/json

{
  "accountId" : "b19f0aa5-1a28-4a5a-81ea-a967dc7ab41b",
  "holderId" : "a169c61a-1e47-41e8-b673-f33db08b522f",
  "amount" : 10
}

###

POST http://localhost:8082/reset