POST http://localhost:8081/holder
Content-Type: application/json

{
  "holderName" : "yoon",
  "tel" : "02-5555-8888",
  "address" : "OO시 OO구",
  "company" : "11 company"
}

###

POST http://localhost:8081/account
Content-Type: application/json

{
  "holderId" : "1c15b418-038c-4499-a9a4-820ae67c38b9"
}

###

POST http://localhost:8081/deposit
Content-Type: application/json

{
  "accountId" : "2a67c4d6-42fb-4763-913a-233cbc5aa59a",
  "holderId" : "3d855aae-9052-45d4-aa99-4337e5593f5d",
  "amount" : 200
}

###

POST http://localhost:8081/withdrawal
Content-Type: application/json

{
  "accountId" : "2a67c4d6-42fb-4763-913a-233cbc5aa59a",
  "holderId" : "3d855aae-9052-45d4-aa99-4337e5593f5d",
  "amount" : 400
}

###

POST http://localhost:8082/reset

###

POST http://localhost:8083/account
Content-Type: application/json

{
  "accountId" : "kakao_park",
  "balance" : 100
}

###

POST http://localhost:8081/transfer
Content-Type: application/json

{
	"srcAccountId" : "kakao_park",
	"dstAccountId" : "2a67c4d6-42fb-4763-913a-233cbc5aa59a",
	"amount" : 10,
	"bankType" : "KAKAO"
}