server:
  port: 8082

spring:
  application:
    name: cqrs-tutorial-query
  datasource:
    url: jdbc:postgresql://localhost:5432/query
    username: query
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      platform: postgres

axon:
  serializer:
    general: xstream

  axon-server:
    servers: localhost:8124

logging:
  level:
    com.cqrs.query: debug
    org.axonframework : debug