server:
  port: 8082

spring:
  application:
    name: cqrs-tutorial-query
  datasource:
    url: jdbc:postgresql://localhost:5432/query
    username: query
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres

axon:
  serializer:
    general: xstream
  axonserver:
    servers: DESKTOP-NVRBMAI:8124