server:
  port: 8081

spring:
  application:
    name: cqrs-tutorial-command
  datasource:
    url: jdbc:postgresql://localhost:5432/command
    username: command
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres

axon:
  serializer:
    general: xstream
  axon-server:
    servers: localhost:8124
